// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5Jl8q253Y_nrd5oEATiI1a8XO6DVEd8',
    appId: '1:212960243876:web:9d1924e0f2876845633631',
    messagingSenderId: '212960243876',
    projectId: 'eazzy-fix',
    authDomain: 'eazzy-fix.firebaseapp.com',
    storageBucket: 'eazzy-fix.appspot.com',
    measurementId: 'G-N32WFBNW96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKt5uLFmhXQacAj40fzhijIufOJsTG8k',
    appId: '1:212960243876:android:e1b5289122dfd850633631',
    messagingSenderId: '212960243876',
    projectId: 'eazzy-fix',
    storageBucket: 'eazzy-fix.appspot.com',
  );
}
